export const emptyData = {
  jobs: [],
  accounts: [],
  contents: [],
  contentVersions: [],
  reviewComments: [],
  assets: [],
  goals: [],
  reports: [],
  entries: [],
  beisenResults: [],
  integrations: [],
  integrationSyncRuns: [],
  modelApis: [],
  landingPages: [],
  landingLeads: [],
  roles: [],
  users: [],
  workflowRules: [],
  sensitiveRules: [],
  costs: [],
  notifications: [],
  auditLogs: [],
};
